From a result file, create inputs file

In [1]:
import pandas as pd
import numpy as np

In [2]:
result_file = '/Users/malo/MIT Dropbox/Malo Lahogue/Research/Generator-outage-probability/Results/Transition_models/GAMS/SMC/GAM__SMC_fullH_GAM__results_test_ALABAMA.csv'

In [3]:
results_df = pd.read_csv(result_file, parse_dates=['Datetime_UTC'])

In [4]:
results_df.head()

,Datetime_UTC,State,Stress,Initial_gen_state,Final_gen_state,Data_weight,pAD,pAO,pDA,pOA,Temperature,Precipitation,Snow_depth,Load_CDF,psi6,psi7,Hours_in_state
0,2022-01-01 00:00:00+00:00,NORTH CAROLINA,2.796372,0.0,0,1.0,0.000016,0.000140,0.000458,0.000268,16.102846,0.252825,2.711864,0.41786,-3.717765,50.8487,3.771661
1,2022-01-01 00:00:00+00:00,NORTH CAROLINA,2.796372,0.0,0,1.0,0.000016,0.000138,0.000456,0.000261,16.102846,0.252825,2.711864,0.41786,-3.717765,50.8487,3.783618
2,2022-01-01 00:00:00+00:00,NORTH CAROLINA,2.796372,0.0,0,1.0,0.000015,0.000132,0.000449,0.000242,16.102846,0.252825,2.711864,0.41786,-3.717765,50.8487,3.816506
3,2022-01-01 00:00:00+00:00,NORTH CAROLINA,2.796372,0.0,0,1.0,0.000010,0.000096,0.000403,0.000144,16.102846,0.252825,2.711864,0.41786,-3.717765,50.8487,4.024527
4,2022-01-01 00:00:00+00:00,NORTH CAROLINA,2.796372,0.0,0,1.0,0.000014,0.000129,0.000446,0.000234,16.102846,0.252825,2.711864,0.41786,-3.717765,50.8487,3.831870

In [5]:
keep_cols = [c for c in results_df.columns if (not c.startswith('pA')) and  
                                              (not c.startswith('pD')) and 
                                              (not c.startswith('pO')) and 
                                              (not c in ['Initial_gen_state', 'Final_gen_state', 'Data_weight'])]

In [6]:
inputs_df = results_df[keep_cols].copy()
inputs_df.drop_duplicates(subset=['Datetime_UTC', 'State'], inplace=True)

In [7]:
inputs_df

,Datetime_UTC,State,Stress,Temperature,Precipitation,Snow_depth,Load_CDF,psi6,psi7,Hours_in_state
0,2022-01-01 00:00:00+00:00,NORTH CAROLINA,2.796372,16.102846,0.252825,2.711864,0.417860,-3.717765,50.848700,3.771661
18,2022-01-01 00:00:00+00:00,NORTH DAKOTA,3.405039,-27.982906,0.272222,2.222222,0.618645,-32.777617,-1.143690,2.245513
45,2022-01-01 00:00:00+00:00,NEW YORK,2.960155,6.310996,0.088261,8.956522,0.513625,-9.599133,43.091910,3.515609
92,2022-01-01 00:00:00+00:00,OKLAHOMA,2.350932,14.858187,0.392019,7.746479,0.618575,-6.273469,44.069298,3.481012
94,2022-01-01 00:00:00+00:00,OHIO,2.828461,9.470985,0.216000,3.100000,0.443542,-6.887775,44.615555,4.392978
...,...,...,...,...,...,...,...,...,...,...
9352763,2022-09-18 01:00:00+00:00,MASSACHUSETTS,2.442962,16.108994,0.391129,3.870968,0.374930,-3.333501,46.463608,1.672098
9352793,2022-09-18 01:00:00+00:00,MARYLAND,2.523916,20.520393,0.378667,2.400000,0.667774,-2.991366,51.880890,3.952211
9352801,2022-09-18 01:00:00+00:00,MAINE,2.418794,12.325455,0.054286,3.142857,0.422792,-5.358700,42.379776,4.151860
9352850,2022-09-18 01:00:00+00:00,IDAHO,1.483510,17.917465,0.172727,8.181818,0.325339,-2.304227,36.350570,2.615950
9352865,2022-09-18 01:00:00+00:00,ILLINOIS,2.443990,22.603765,0.423737,1.212121,0.762490,-1.827104,52.971157,2.984077

In [8]:
inputs_df.to_csv(f"../DATA/hourly/scenario_inputs_test_2022-2023.csv", index=False)